const monstersList = [{
  slug: 'aboleth',
  name: 'Aboleth',
  size: 'Large',
  type: 'aberration',
  subtype: '',
  group: null,
  alignment: 'lawful evil',
  armor_class: 17,
  armor_desc: 'natural armor',
  hit_points: 135,
  hit_dice: '18d10+36',
  speed: {
    walk: 10,
    swim: 40,
  },
  strength: 21,
  dexterity: 9,
  constitution: 15,
  intelligence: 18,
  wisdom: 15,
  charisma: 18,
  strength_save: null,
  dexterity_save: null,
  constitution_save: 6,
  intelligence_save: 8,
  wisdom_save: 6,
  charisma_save: null,
  perception: 10,
  skills: {
    history: 12,
    perception: 10,
  },
  damage_vulnerabilities: '',
  damage_resistances: '',
  damage_immunities: '',
  condition_immunities: '',
  senses: 'darkvision 120 ft., passive Perception 20',
  languages: 'Deep Speech, telepathy 120 ft.',
  challenge_rating: '10',
  spell_list: [],
  img_main: 'http://api.open5e.com/static/img/monsters/aboleth.png',
  document__slug: 'wotc-srd',
  document__title: 'Systems Reference Document',
  document__license_url: 'http://open5e.com/legal',
  id: 'aboleth',
  challenge: '10',
}];
export default monstersList;
